#include <dirent.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "primelist.h"

#define FILE_PATH_SIZE 512

/**
 * @brief Allocates and initializes a new PrimeList structure to hold up to max_primes integers.
 *
 * This function dynamically allocates memory for a PrimeList structure, including space for
 * an array of integers to store prime numbers. The number of primes currently stored is
 * initialized to zero.
 *
 * @param max_primes The maximum number of prime numbers the list can hold.
 * @return Pointer to the newly allocated PrimeList structure, or NULL if allocation fails.
 */
PrimeList* new_prime_list(size_t max_primes) {
    PrimeList* pl = malloc(sizeof(PrimeList) + (max_primes * sizeof(int)));
    if (!pl) return NULL;
    pl->num_primes = 0;

    return pl;
}




/**
 * @brief Reads prime numbers from files in the specified directory and stores them in a PrimeList.
 *
 * This function opens the given directory, iterates through all files excluding "." and "..",
 * and reads each line from the files in the "prime_files/" subdirectory. Each line is expected
 * to contain a prime number, which is converted to an integer and added to the PrimeList.
 *
 * @param pl Pointer to a PrimeList structure where the primes will be stored.
 * @param dir_name Name of the directory containing the prime files.
 * @return 0 on success, -1 on failure (if the directory or a file cannot be opened).
 */
int get_primes(PrimeList* pl, const char* dir_name) {
    system("cd prime_files/");

    DIR* dir;
    struct dirent* dp;

    if ((dir = opendir(dir_name)) == NULL) {
        printf("Could not open file %s.\n", dir_name);
        return -1;
    }

    while ((dp = readdir(dir)) != NULL) {
        /*
            Do not touch current dir or parent dir.
            "." || ".."
        */
        if (strcmp(dp->d_name, ".") == 0 || strcmp(dp->d_name, "..") == 0)
            continue;
        
        /*
            Open files generated by worker according to their PID
        */
        char path[FILE_PATH_SIZE] = "prime_files/";
        strcat(path, dp->d_name);
        FILE* file = fopen(path, "r");
        if (file == NULL) {printf("Error opening file: %s\n", path); return -1;}
        
        /*
            Retrieve all lines in each file and push them into prime_list
            array.
        */
        char* line = NULL;
        size_t len = 0;
        ssize_t read;
        while ((read = getline(&line, &len, file)) != -1) {
            pl->primes[pl->num_primes++] = atoi(line);
        }

        /*
            Must free line because there is a hidden allocation in 
            getline().
        */
        free(line);
        fclose(file);
    }

    return 0;
}

